<?php
acf_add_local_field_group(
	array(
		'key'                   => 'group_66fd649487de8',
		'title'                 => esc_attr__( 'Options', 'alben' ),
		'fields'                => array(
			array(
				'key'               => 'field_66fd6494b0bd8',
				'label'             => esc_attr__( 'General', 'alben' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_66fd64c9b0bd9',
				'label'             => esc_attr__( 'Logo Title', 'alben' ),
				'name'              => 'acf_logo_title',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => 'AlBen',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_66fd64c9b0ht6',
				'label'             => esc_attr__( 'Email', 'alben' ),
				'name'              => 'acf_email',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_66fd64c9b0op7',
				'label'             => esc_attr__( 'Phone', 'alben' ),
				'name'              => 'acf_phone',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_66fd64c9b0hhm2',
				'label'             => esc_attr__( 'Copyright', 'alben' ),
				'name'              => 'acf_copyright',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => '[current-year] ' . esc_attr__( 'placeholder is used', 'alben' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_66fe5d5615751',
				'label'             => esc_attr__( 'Social', 'alben' ),
				'name'              => 'acf_social',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 0,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Add Row', 'alben' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_66fe5d7415752',
						'label'             => esc_attr__( 'Icon', 'alben' ),
						'name'              => 'icon',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => 10,
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'id',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'allow_in_bindings' => 0,
						'preview_size'      => 'medium',
						'parent_repeater'   => 'field_66fe5d5615751',
					),
					array(
						'key'               => 'field_66fe5d9d15753',
						'label'             => esc_attr__( 'Link', 'alben' ),
						'name'              => 'link',
						'aria-label'        => '',
						'type'              => 'url',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => 90,
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'parent_repeater'   => 'field_66fe5d5615751',
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'alben-options',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
		'show_in_rest'          => 0,
	)
);
